---
title: "About"
sidemenu: "true"
date: "`r Sys.Date()`"
---

안녕하세요. 
저는 [중앙대학교 통계학과](https://stat.cau.ac.kr/)에서 **통계학**을 공부하고 있는 박사과정 학생입니다.
현재 [다변량 분석 연구실(Multivariate Data Analysis Lab)](https://sites.google.com/site/yaejilim/)에서 `Functional Data Analysis`에 대한 연구를 하고 있습니다.

**R**로 코딩하고, **Rmarkdown**으로 문서 작성하는 것을 좋아하며, **통계학**이나 **R programming**에 대해 공부하며 알게된 내용들을 가끔식 블로그에 정리하고 있습니다. 


## Research Interests
- `Functional Data Analysis`
- `Spatio-temporal Data Analysis`
- `High-dimensional Data Analysis`


## Education
- **중앙대 통계학과 박사과정**, 2021.03 - Present
- **중앙대 통계학 석사**, 2019.03 - 2021.02
  - Thesis : Bootstrap aggregated classification for sparse functional data.
- **중앙대 응용통계학 학사**, 2013.03 - 2019.02


## Publications
- **Kim, H.**, & Lim, Y. (2021). [Bootstrap aggregated classification for sparse functional data](https://doi.org/10.1080/02664763.2021.1889997). *Journal
of Applied Statistics*, In press.
- **Kim, H.**, Li, X., & Lim, Y. (2021). Robust group independent component analysis. *The Korean Journal
of Applied Statistics*, 34(2), 135–147.


## Projects
- **경기도 고혈압·당뇨병 등록관리사업 효과평가 분석**, *중앙의대 예방의학교실*, 2019.07 - 2020.02
- **빅데이터 기반 서비스부품 수요예측 강화**, *부품운영팀, 현대모비스*, 2019.02 - 2019.09


## Teaching Experience
- **Teaching Assistant**, Introduction to Statistical Learning, *Department of Applied Statistics, Chung-Ang University*, 2019 Fall


## [Curriculum Vitae](https://nbviewer.jupyter.org/github/statKim/CV_KHS/blob/master/CV.pdf)
